/*
 * vpc
 * VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
 *
 * OpenAPI spec version: 2020-10-22T13:56:07Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vpc.model;

import java.util.Objects;

/**
 * CreateNatGatewayInstanceRequest
 */
public class CreateNatGatewayInstanceRequest {
	private String regionCode = null;

	private String natGatewayDescription = null;

	private String natGatewayName = null;

	private String vpcNo = null;

	private String zoneCode = null;

	private String responseFormatType = null;

	public CreateNatGatewayInstanceRequest regionCode(String regionCode) {
		this.regionCode = regionCode;
		return this;
	}

	 /**
	 * REGION코드
	 * @return regionCode
	**/
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public CreateNatGatewayInstanceRequest natGatewayDescription(String natGatewayDescription) {
		this.natGatewayDescription = natGatewayDescription;
		return this;
	}

	 /**
	 * NATGateway설명
	 * @return natGatewayDescription
	**/
	public String getNatGatewayDescription() {
		return natGatewayDescription;
	}

	public void setNatGatewayDescription(String natGatewayDescription) {
		this.natGatewayDescription = natGatewayDescription;
	}

	public CreateNatGatewayInstanceRequest natGatewayName(String natGatewayName) {
		this.natGatewayName = natGatewayName;
		return this;
	}

	 /**
	 * NATGateway이름
	 * @return natGatewayName
	**/
	public String getNatGatewayName() {
		return natGatewayName;
	}

	public void setNatGatewayName(String natGatewayName) {
		this.natGatewayName = natGatewayName;
	}

	public CreateNatGatewayInstanceRequest vpcNo(String vpcNo) {
		this.vpcNo = vpcNo;
		return this;
	}

	 /**
	 * VPC번호
	 * @return vpcNo
	**/
	public String getVpcNo() {
		return vpcNo;
	}

	public void setVpcNo(String vpcNo) {
		this.vpcNo = vpcNo;
	}

	public CreateNatGatewayInstanceRequest zoneCode(String zoneCode) {
		this.zoneCode = zoneCode;
		return this;
	}

	 /**
	 * ZONE코드
	 * @return zoneCode
	**/
	public String getZoneCode() {
		return zoneCode;
	}

	public void setZoneCode(String zoneCode) {
		this.zoneCode = zoneCode;
	}

	public CreateNatGatewayInstanceRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CreateNatGatewayInstanceRequest createNatGatewayInstanceRequest = (CreateNatGatewayInstanceRequest) o;
		return Objects.equals(this.regionCode, createNatGatewayInstanceRequest.regionCode) &&
				Objects.equals(this.natGatewayDescription, createNatGatewayInstanceRequest.natGatewayDescription) &&
				Objects.equals(this.natGatewayName, createNatGatewayInstanceRequest.natGatewayName) &&
				Objects.equals(this.vpcNo, createNatGatewayInstanceRequest.vpcNo) &&
				Objects.equals(this.zoneCode, createNatGatewayInstanceRequest.zoneCode) &&
				Objects.equals(this.responseFormatType, createNatGatewayInstanceRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(regionCode, natGatewayDescription, natGatewayName, vpcNo, zoneCode, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CreateNatGatewayInstanceRequest {\n");
		
		sb.append("		regionCode: ").append(toIndentedString(regionCode)).append("\n");
		sb.append("		natGatewayDescription: ").append(toIndentedString(natGatewayDescription)).append("\n");
		sb.append("		natGatewayName: ").append(toIndentedString(natGatewayName)).append("\n");
		sb.append("		vpcNo: ").append(toIndentedString(vpcNo)).append("\n");
		sb.append("		zoneCode: ").append(toIndentedString(zoneCode)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

