/*
 * vpc
 * VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vpc.model;

import java.util.Objects;
import com.ncloud.vpc.model.NetworkAclDenyAllowGroup;
import java.util.ArrayList;
import java.util.List;

/**
 * DeleteNetworkAclDenyAllowGroupResponse
 */
public class DeleteNetworkAclDenyAllowGroupResponse {
	private String requestId = null;

	private String returnCode = null;

	private String returnMessage = null;

	private Integer totalRows = null;

	private List<NetworkAclDenyAllowGroup> networkAclDenyAllowGroupList = null;

	public DeleteNetworkAclDenyAllowGroupResponse requestId(String requestId) {
		this.requestId = requestId;
		return this;
	}

	 /**
	 * Get requestId
	 * @return requestId
	**/
	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public DeleteNetworkAclDenyAllowGroupResponse returnCode(String returnCode) {
		this.returnCode = returnCode;
		return this;
	}

	 /**
	 * Get returnCode
	 * @return returnCode
	**/
	public String getReturnCode() {
		return returnCode;
	}

	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	public DeleteNetworkAclDenyAllowGroupResponse returnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
		return this;
	}

	 /**
	 * Get returnMessage
	 * @return returnMessage
	**/
	public String getReturnMessage() {
		return returnMessage;
	}

	public void setReturnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
	}

	public DeleteNetworkAclDenyAllowGroupResponse totalRows(Integer totalRows) {
		this.totalRows = totalRows;
		return this;
	}

	 /**
	 * Get totalRows
	 * @return totalRows
	**/
	public Integer getTotalRows() {
		return totalRows;
	}

	public void setTotalRows(Integer totalRows) {
		this.totalRows = totalRows;
	}

	public DeleteNetworkAclDenyAllowGroupResponse networkAclDenyAllowGroupList(List<NetworkAclDenyAllowGroup> networkAclDenyAllowGroupList) {
		this.networkAclDenyAllowGroupList = networkAclDenyAllowGroupList;
		return this;
	}

	public DeleteNetworkAclDenyAllowGroupResponse addNetworkAclDenyAllowGroupListItem(NetworkAclDenyAllowGroup networkAclDenyAllowGroupListItem) {
		if (this.networkAclDenyAllowGroupList == null) {
			this.networkAclDenyAllowGroupList = new ArrayList<NetworkAclDenyAllowGroup>();
		}
		this.networkAclDenyAllowGroupList.add(networkAclDenyAllowGroupListItem);
		return this;
	}

	 /**
	 * Get networkAclDenyAllowGroupList
	 * @return networkAclDenyAllowGroupList
	**/
	public List<NetworkAclDenyAllowGroup> getNetworkAclDenyAllowGroupList() {
		return networkAclDenyAllowGroupList;
	}

	public void setNetworkAclDenyAllowGroupList(List<NetworkAclDenyAllowGroup> networkAclDenyAllowGroupList) {
		this.networkAclDenyAllowGroupList = networkAclDenyAllowGroupList;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		DeleteNetworkAclDenyAllowGroupResponse deleteNetworkAclDenyAllowGroupResponse = (DeleteNetworkAclDenyAllowGroupResponse) o;
		return Objects.equals(this.requestId, deleteNetworkAclDenyAllowGroupResponse.requestId) &&
				Objects.equals(this.returnCode, deleteNetworkAclDenyAllowGroupResponse.returnCode) &&
				Objects.equals(this.returnMessage, deleteNetworkAclDenyAllowGroupResponse.returnMessage) &&
				Objects.equals(this.totalRows, deleteNetworkAclDenyAllowGroupResponse.totalRows) &&
				Objects.equals(this.networkAclDenyAllowGroupList, deleteNetworkAclDenyAllowGroupResponse.networkAclDenyAllowGroupList);
	}

	@Override
	public int hashCode() {
		return Objects.hash(requestId, returnCode, returnMessage, totalRows, networkAclDenyAllowGroupList);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class DeleteNetworkAclDenyAllowGroupResponse {\n");
		
		sb.append("		requestId: ").append(toIndentedString(requestId)).append("\n");
		sb.append("		returnCode: ").append(toIndentedString(returnCode)).append("\n");
		sb.append("		returnMessage: ").append(toIndentedString(returnMessage)).append("\n");
		sb.append("		totalRows: ").append(toIndentedString(totalRows)).append("\n");
		sb.append("		networkAclDenyAllowGroupList: ").append(toIndentedString(networkAclDenyAllowGroupList)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

