/*
 * vpc
 * VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
 *
 * OpenAPI spec version: 2020-10-22T13:56:07Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vpc.model;

import java.util.Objects;

/**
 * GetNetworkAclRuleListRequest
 */
public class GetNetworkAclRuleListRequest {
	private String regionCode = null;

	private String networkAclNo = null;

	private String networkAclRuleTypeCode = null;

	private String responseFormatType = null;

	public GetNetworkAclRuleListRequest regionCode(String regionCode) {
		this.regionCode = regionCode;
		return this;
	}

	 /**
	 * REGION코드
	 * @return regionCode
	**/
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public GetNetworkAclRuleListRequest networkAclNo(String networkAclNo) {
		this.networkAclNo = networkAclNo;
		return this;
	}

	 /**
	 * 네트워크ACL번호
	 * @return networkAclNo
	**/
	public String getNetworkAclNo() {
		return networkAclNo;
	}

	public void setNetworkAclNo(String networkAclNo) {
		this.networkAclNo = networkAclNo;
	}

	public GetNetworkAclRuleListRequest networkAclRuleTypeCode(String networkAclRuleTypeCode) {
		this.networkAclRuleTypeCode = networkAclRuleTypeCode;
		return this;
	}

	 /**
	 * 네트워크ACLRule유형코드
	 * @return networkAclRuleTypeCode
	**/
	public String getNetworkAclRuleTypeCode() {
		return networkAclRuleTypeCode;
	}

	public void setNetworkAclRuleTypeCode(String networkAclRuleTypeCode) {
		this.networkAclRuleTypeCode = networkAclRuleTypeCode;
	}

	public GetNetworkAclRuleListRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetNetworkAclRuleListRequest getNetworkAclRuleListRequest = (GetNetworkAclRuleListRequest) o;
		return Objects.equals(this.regionCode, getNetworkAclRuleListRequest.regionCode) &&
				Objects.equals(this.networkAclNo, getNetworkAclRuleListRequest.networkAclNo) &&
				Objects.equals(this.networkAclRuleTypeCode, getNetworkAclRuleListRequest.networkAclRuleTypeCode) &&
				Objects.equals(this.responseFormatType, getNetworkAclRuleListRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(regionCode, networkAclNo, networkAclRuleTypeCode, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetNetworkAclRuleListRequest {\n");
		
		sb.append("		regionCode: ").append(toIndentedString(regionCode)).append("\n");
		sb.append("		networkAclNo: ").append(toIndentedString(networkAclNo)).append("\n");
		sb.append("		networkAclRuleTypeCode: ").append(toIndentedString(networkAclRuleTypeCode)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

