/*
 * vpc
 * VPC Network 관련 API<br/>https://ncloud.apigw.ntruss.com/vpc/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vpc.model;

import java.util.Objects;

/**
 * GetRouteTableSubnetListRequest
 */
public class GetRouteTableSubnetListRequest {
	private String regionCode = null;

	private String routeTableNo = null;

	private String responseFormatType = null;

	public GetRouteTableSubnetListRequest regionCode(String regionCode) {
		this.regionCode = regionCode;
		return this;
	}

	 /**
	 * REGION코드
	 * @return regionCode
	**/
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public GetRouteTableSubnetListRequest routeTableNo(String routeTableNo) {
		this.routeTableNo = routeTableNo;
		return this;
	}

	 /**
	 * 라우트테이블번호
	 * @return routeTableNo
	**/
	public String getRouteTableNo() {
		return routeTableNo;
	}

	public void setRouteTableNo(String routeTableNo) {
		this.routeTableNo = routeTableNo;
	}

	public GetRouteTableSubnetListRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetRouteTableSubnetListRequest getRouteTableSubnetListRequest = (GetRouteTableSubnetListRequest) o;
		return Objects.equals(this.regionCode, getRouteTableSubnetListRequest.regionCode) &&
				Objects.equals(this.routeTableNo, getRouteTableSubnetListRequest.routeTableNo) &&
				Objects.equals(this.responseFormatType, getRouteTableSubnetListRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(regionCode, routeTableNo, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetRouteTableSubnetListRequest {\n");
		
		sb.append("		regionCode: ").append(toIndentedString(regionCode)).append("\n");
		sb.append("		routeTableNo: ").append(toIndentedString(routeTableNo)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

