/*
 * vnas
 * VPC NAS 관련 API<br/>https://ncloud.apigw.ntruss.com/vnas/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vnas.model;

import java.util.Objects;

/**
 * NasVolumeAccessControlRule
 */
public class NasVolumeAccessControlRule {
	private String serverInstanceNo = null;

	private Boolean readAccess = null;

	private Boolean writeAccess = null;

	public NasVolumeAccessControlRule serverInstanceNo(String serverInstanceNo) {
		this.serverInstanceNo = serverInstanceNo;
		return this;
	}

	 /**
	 * 서버인스턴스번호
	 * @return serverInstanceNo
	**/
	public String getServerInstanceNo() {
		return serverInstanceNo;
	}

	public void setServerInstanceNo(String serverInstanceNo) {
		this.serverInstanceNo = serverInstanceNo;
	}

	public NasVolumeAccessControlRule readAccess(Boolean readAccess) {
		this.readAccess = readAccess;
		return this;
	}

	 /**
	 * ReadAccess여부
	 * @return readAccess
	**/
	public Boolean isReadAccess() {
		return readAccess;
	}

	public void setReadAccess(Boolean readAccess) {
		this.readAccess = readAccess;
	}

	public NasVolumeAccessControlRule writeAccess(Boolean writeAccess) {
		this.writeAccess = writeAccess;
		return this;
	}

	 /**
	 * WriteAccess여부
	 * @return writeAccess
	**/
	public Boolean isWriteAccess() {
		return writeAccess;
	}

	public void setWriteAccess(Boolean writeAccess) {
		this.writeAccess = writeAccess;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		NasVolumeAccessControlRule nasVolumeAccessControlRule = (NasVolumeAccessControlRule) o;
		return Objects.equals(this.serverInstanceNo, nasVolumeAccessControlRule.serverInstanceNo) &&
				Objects.equals(this.readAccess, nasVolumeAccessControlRule.readAccess) &&
				Objects.equals(this.writeAccess, nasVolumeAccessControlRule.writeAccess);
	}

	@Override
	public int hashCode() {
		return Objects.hash(serverInstanceNo, readAccess, writeAccess);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class NasVolumeAccessControlRule {\n");
		
		sb.append("		serverInstanceNo: ").append(toIndentedString(serverInstanceNo)).append("\n");
		sb.append("		readAccess: ").append(toIndentedString(readAccess)).append("\n");
		sb.append("		writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

