/*
 * clouddb
 * Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
 *
 * OpenAPI spec version: 2018-11-13T06:30:03Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.clouddb.model;

import java.util.Objects;
import com.ncloud.clouddb.model.CommonCode;

/**
 * CloudDBServerInstance
 */
public class CloudDBServerInstance {
	private String cloudDBServerInstanceNo = null;

	private String cloudDBServerInstanceStatusName = null;

	private String cloudDBServerName = null;

	private CommonCode cloudDBServerRole = null;

	private String privateDnsName = null;

	private String publicDnsName = null;

	private Long dataStorageSize = null;

	private Long usedDataStorageSize = null;

	private String createDate = null;

	private String uptime = null;

	public CloudDBServerInstance cloudDBServerInstanceNo(String cloudDBServerInstanceNo) {
		this.cloudDBServerInstanceNo = cloudDBServerInstanceNo;
		return this;
	}

	 /**
	 * CloudDB서버인스턴스번호
	 * @return cloudDBServerInstanceNo
	**/
	public String getCloudDBServerInstanceNo() {
		return cloudDBServerInstanceNo;
	}

	public void setCloudDBServerInstanceNo(String cloudDBServerInstanceNo) {
		this.cloudDBServerInstanceNo = cloudDBServerInstanceNo;
	}

	public CloudDBServerInstance cloudDBServerInstanceStatusName(String cloudDBServerInstanceStatusName) {
		this.cloudDBServerInstanceStatusName = cloudDBServerInstanceStatusName;
		return this;
	}

	 /**
	 * CloudDB서버인스턴스상태이름
	 * @return cloudDBServerInstanceStatusName
	**/
	public String getCloudDBServerInstanceStatusName() {
		return cloudDBServerInstanceStatusName;
	}

	public void setCloudDBServerInstanceStatusName(String cloudDBServerInstanceStatusName) {
		this.cloudDBServerInstanceStatusName = cloudDBServerInstanceStatusName;
	}

	public CloudDBServerInstance cloudDBServerName(String cloudDBServerName) {
		this.cloudDBServerName = cloudDBServerName;
		return this;
	}

	 /**
	 * CloudDB서버이름
	 * @return cloudDBServerName
	**/
	public String getCloudDBServerName() {
		return cloudDBServerName;
	}

	public void setCloudDBServerName(String cloudDBServerName) {
		this.cloudDBServerName = cloudDBServerName;
	}

	public CloudDBServerInstance cloudDBServerRole(CommonCode cloudDBServerRole) {
		this.cloudDBServerRole = cloudDBServerRole;
		return this;
	}

	 /**
	 * CloudDB서버역할
	 * @return cloudDBServerRole
	**/
	public CommonCode getCloudDBServerRole() {
		return cloudDBServerRole;
	}

	public void setCloudDBServerRole(CommonCode cloudDBServerRole) {
		this.cloudDBServerRole = cloudDBServerRole;
	}

	public CloudDBServerInstance privateDnsName(String privateDnsName) {
		this.privateDnsName = privateDnsName;
		return this;
	}

	 /**
	 * 사설DNS이름
	 * @return privateDnsName
	**/
	public String getPrivateDnsName() {
		return privateDnsName;
	}

	public void setPrivateDnsName(String privateDnsName) {
		this.privateDnsName = privateDnsName;
	}

	public CloudDBServerInstance publicDnsName(String publicDnsName) {
		this.publicDnsName = publicDnsName;
		return this;
	}

	 /**
	 * 공인DNS이름
	 * @return publicDnsName
	**/
	public String getPublicDnsName() {
		return publicDnsName;
	}

	public void setPublicDnsName(String publicDnsName) {
		this.publicDnsName = publicDnsName;
	}

	public CloudDBServerInstance dataStorageSize(Long dataStorageSize) {
		this.dataStorageSize = dataStorageSize;
		return this;
	}

	 /**
	 * 데이터스토리지사이즈
	 * @return dataStorageSize
	**/
	public Long getDataStorageSize() {
		return dataStorageSize;
	}

	public void setDataStorageSize(Long dataStorageSize) {
		this.dataStorageSize = dataStorageSize;
	}

	public CloudDBServerInstance usedDataStorageSize(Long usedDataStorageSize) {
		this.usedDataStorageSize = usedDataStorageSize;
		return this;
	}

	 /**
	 * 사용데이터스토리지사이즈
	 * @return usedDataStorageSize
	**/
	public Long getUsedDataStorageSize() {
		return usedDataStorageSize;
	}

	public void setUsedDataStorageSize(Long usedDataStorageSize) {
		this.usedDataStorageSize = usedDataStorageSize;
	}

	public CloudDBServerInstance createDate(String createDate) {
		this.createDate = createDate;
		return this;
	}

	 /**
	 * 생성일시
	 * @return createDate
	**/
	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public CloudDBServerInstance uptime(String uptime) {
		this.uptime = uptime;
		return this;
	}

	 /**
	 * 구동시간
	 * @return uptime
	**/
	public String getUptime() {
		return uptime;
	}

	public void setUptime(String uptime) {
		this.uptime = uptime;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CloudDBServerInstance cloudDBServerInstance = (CloudDBServerInstance) o;
		return Objects.equals(this.cloudDBServerInstanceNo, cloudDBServerInstance.cloudDBServerInstanceNo) &&
				Objects.equals(this.cloudDBServerInstanceStatusName, cloudDBServerInstance.cloudDBServerInstanceStatusName) &&
				Objects.equals(this.cloudDBServerName, cloudDBServerInstance.cloudDBServerName) &&
				Objects.equals(this.cloudDBServerRole, cloudDBServerInstance.cloudDBServerRole) &&
				Objects.equals(this.privateDnsName, cloudDBServerInstance.privateDnsName) &&
				Objects.equals(this.publicDnsName, cloudDBServerInstance.publicDnsName) &&
				Objects.equals(this.dataStorageSize, cloudDBServerInstance.dataStorageSize) &&
				Objects.equals(this.usedDataStorageSize, cloudDBServerInstance.usedDataStorageSize) &&
				Objects.equals(this.createDate, cloudDBServerInstance.createDate) &&
				Objects.equals(this.uptime, cloudDBServerInstance.uptime);
	}

	@Override
	public int hashCode() {
		return Objects.hash(cloudDBServerInstanceNo, cloudDBServerInstanceStatusName, cloudDBServerName, cloudDBServerRole, privateDnsName, publicDnsName, dataStorageSize, usedDataStorageSize, createDate, uptime);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CloudDBServerInstance {\n");
		
		sb.append("		cloudDBServerInstanceNo: ").append(toIndentedString(cloudDBServerInstanceNo)).append("\n");
		sb.append("		cloudDBServerInstanceStatusName: ").append(toIndentedString(cloudDBServerInstanceStatusName)).append("\n");
		sb.append("		cloudDBServerName: ").append(toIndentedString(cloudDBServerName)).append("\n");
		sb.append("		cloudDBServerRole: ").append(toIndentedString(cloudDBServerRole)).append("\n");
		sb.append("		privateDnsName: ").append(toIndentedString(privateDnsName)).append("\n");
		sb.append("		publicDnsName: ").append(toIndentedString(publicDnsName)).append("\n");
		sb.append("		dataStorageSize: ").append(toIndentedString(dataStorageSize)).append("\n");
		sb.append("		usedDataStorageSize: ").append(toIndentedString(usedDataStorageSize)).append("\n");
		sb.append("		createDate: ").append(toIndentedString(createDate)).append("\n");
		sb.append("		uptime: ").append(toIndentedString(uptime)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

