/*
 * clouddb
 * Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.clouddb.model;

import java.util.Objects;

/**
 * ExportDbServerLogToObjectStorageRequest
 */
public class ExportDbServerLogToObjectStorageRequest {
	private String regionNo = null;

	private String dbKindCode = null;

	private String fileName = null;

	private String bucketName = null;

	private String cloudDBInstanceNo = null;

	private String cloudDBServerInstanceNo = null;

	private String logType = null;

	private String responseFormatType = null;

	public ExportDbServerLogToObjectStorageRequest regionNo(String regionNo) {
		this.regionNo = regionNo;
		return this;
	}

	 /**
	 * 리전번호
	 * @return regionNo
	**/
	public String getRegionNo() {
		return regionNo;
	}

	public void setRegionNo(String regionNo) {
		this.regionNo = regionNo;
	}

	public ExportDbServerLogToObjectStorageRequest dbKindCode(String dbKindCode) {
		this.dbKindCode = dbKindCode;
		return this;
	}

	 /**
	 * DB코드 (MYSQL)
	 * @return dbKindCode
	**/
	public String getDbKindCode() {
		return dbKindCode;
	}

	public void setDbKindCode(String dbKindCode) {
		this.dbKindCode = dbKindCode;
	}

	public ExportDbServerLogToObjectStorageRequest fileName(String fileName) {
		this.fileName = fileName;
		return this;
	}

	 /**
	 * 파일명
	 * @return fileName
	**/
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public ExportDbServerLogToObjectStorageRequest bucketName(String bucketName) {
		this.bucketName = bucketName;
		return this;
	}

	 /**
	 * 버킷명
	 * @return bucketName
	**/
	public String getBucketName() {
		return bucketName;
	}

	public void setBucketName(String bucketName) {
		this.bucketName = bucketName;
	}

	public ExportDbServerLogToObjectStorageRequest cloudDBInstanceNo(String cloudDBInstanceNo) {
		this.cloudDBInstanceNo = cloudDBInstanceNo;
		return this;
	}

	 /**
	 * CloudDB인스턴스번호
	 * @return cloudDBInstanceNo
	**/
	public String getCloudDBInstanceNo() {
		return cloudDBInstanceNo;
	}

	public void setCloudDBInstanceNo(String cloudDBInstanceNo) {
		this.cloudDBInstanceNo = cloudDBInstanceNo;
	}

	public ExportDbServerLogToObjectStorageRequest cloudDBServerInstanceNo(String cloudDBServerInstanceNo) {
		this.cloudDBServerInstanceNo = cloudDBServerInstanceNo;
		return this;
	}

	 /**
	 * CloudDB 서버인스턴스번호
	 * @return cloudDBServerInstanceNo
	**/
	public String getCloudDBServerInstanceNo() {
		return cloudDBServerInstanceNo;
	}

	public void setCloudDBServerInstanceNo(String cloudDBServerInstanceNo) {
		this.cloudDBServerInstanceNo = cloudDBServerInstanceNo;
	}

	public ExportDbServerLogToObjectStorageRequest logType(String logType) {
		this.logType = logType;
		return this;
	}

	 /**
	 * BINARY/ERROR/SLOW/GENERAL
	 * @return logType
	**/
	public String getLogType() {
		return logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public ExportDbServerLogToObjectStorageRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ExportDbServerLogToObjectStorageRequest exportDbServerLogToObjectStorageRequest = (ExportDbServerLogToObjectStorageRequest) o;
		return Objects.equals(this.regionNo, exportDbServerLogToObjectStorageRequest.regionNo) &&
				Objects.equals(this.dbKindCode, exportDbServerLogToObjectStorageRequest.dbKindCode) &&
				Objects.equals(this.fileName, exportDbServerLogToObjectStorageRequest.fileName) &&
				Objects.equals(this.bucketName, exportDbServerLogToObjectStorageRequest.bucketName) &&
				Objects.equals(this.cloudDBInstanceNo, exportDbServerLogToObjectStorageRequest.cloudDBInstanceNo) &&
				Objects.equals(this.cloudDBServerInstanceNo, exportDbServerLogToObjectStorageRequest.cloudDBServerInstanceNo) &&
				Objects.equals(this.logType, exportDbServerLogToObjectStorageRequest.logType) &&
				Objects.equals(this.responseFormatType, exportDbServerLogToObjectStorageRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(regionNo, dbKindCode, fileName, bucketName, cloudDBInstanceNo, cloudDBServerInstanceNo, logType, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ExportDbServerLogToObjectStorageRequest {\n");
		
		sb.append("		regionNo: ").append(toIndentedString(regionNo)).append("\n");
		sb.append("		dbKindCode: ").append(toIndentedString(dbKindCode)).append("\n");
		sb.append("		fileName: ").append(toIndentedString(fileName)).append("\n");
		sb.append("		bucketName: ").append(toIndentedString(bucketName)).append("\n");
		sb.append("		cloudDBInstanceNo: ").append(toIndentedString(cloudDBInstanceNo)).append("\n");
		sb.append("		cloudDBServerInstanceNo: ").append(toIndentedString(cloudDBServerInstanceNo)).append("\n");
		sb.append("		logType: ").append(toIndentedString(logType)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

