/*
 * clouddb
 * Cloud DB<br/>https://ncloud.apigw.ntruss.com/clouddb/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.clouddb.model;

import java.util.Objects;

/**
 * RestoreDmsDatabaseResponse
 */
public class RestoreDmsDatabaseResponse {
	private String requestId = null;

	private String returnCode = null;

	private String returnMessage = null;

	private String requestNo = null;

	public RestoreDmsDatabaseResponse requestId(String requestId) {
		this.requestId = requestId;
		return this;
	}

	 /**
	 * Get requestId
	 * @return requestId
	**/
	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public RestoreDmsDatabaseResponse returnCode(String returnCode) {
		this.returnCode = returnCode;
		return this;
	}

	 /**
	 * Get returnCode
	 * @return returnCode
	**/
	public String getReturnCode() {
		return returnCode;
	}

	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	public RestoreDmsDatabaseResponse returnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
		return this;
	}

	 /**
	 * Get returnMessage
	 * @return returnMessage
	**/
	public String getReturnMessage() {
		return returnMessage;
	}

	public void setReturnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
	}

	public RestoreDmsDatabaseResponse requestNo(String requestNo) {
		this.requestNo = requestNo;
		return this;
	}

	 /**
	 * Get requestNo
	 * @return requestNo
	**/
	public String getRequestNo() {
		return requestNo;
	}

	public void setRequestNo(String requestNo) {
		this.requestNo = requestNo;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RestoreDmsDatabaseResponse restoreDmsDatabaseResponse = (RestoreDmsDatabaseResponse) o;
		return Objects.equals(this.requestId, restoreDmsDatabaseResponse.requestId) &&
				Objects.equals(this.returnCode, restoreDmsDatabaseResponse.returnCode) &&
				Objects.equals(this.returnMessage, restoreDmsDatabaseResponse.returnMessage) &&
				Objects.equals(this.requestNo, restoreDmsDatabaseResponse.requestNo);
	}

	@Override
	public int hashCode() {
		return Objects.hash(requestId, returnCode, returnMessage, requestNo);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RestoreDmsDatabaseResponse {\n");
		
		sb.append("		requestId: ").append(toIndentedString(requestId)).append("\n");
		sb.append("		returnCode: ").append(toIndentedString(returnCode)).append("\n");
		sb.append("		returnMessage: ").append(toIndentedString(returnMessage)).append("\n");
		sb.append("		requestNo: ").append(toIndentedString(requestNo)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

