/*
 * server
 * <br/>https://ncloud.apigw.ntruss.com/server/v2
 *
 * OpenAPI spec version: 2020-11-18T09:44:01Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.server.model;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * CreateNasVolumeInstanceRequest
 */
public class CreateNasVolumeInstanceRequest {
	private String volumeName = null;

	private Integer volumeSize = null;

	private String volumeAllotmentProtocolTypeCode = null;

	private List<String> serverInstanceNoList = null;

	private List<String> customIpList = null;

	private String cifsUserName = null;

	private String cifsUserPassword = null;

	private String nasVolumeDescription = null;

	private String regionNo = null;

	private String zoneNo = null;

	private String responseFormatType = null;

	public CreateNasVolumeInstanceRequest volumeName(String volumeName) {
		this.volumeName = volumeName;
		return this;
	}

	 /**
	 * 볼륨이름
	 * @return volumeName
	**/
	public String getVolumeName() {
		return volumeName;
	}

	public void setVolumeName(String volumeName) {
		this.volumeName = volumeName;
	}

	public CreateNasVolumeInstanceRequest volumeSize(Integer volumeSize) {
		this.volumeSize = volumeSize;
		return this;
	}

	 /**
	 * NAS볼륨사이즈
	 * @return volumeSize
	**/
	public Integer getVolumeSize() {
		return volumeSize;
	}

	public void setVolumeSize(Integer volumeSize) {
		this.volumeSize = volumeSize;
	}

	public CreateNasVolumeInstanceRequest volumeAllotmentProtocolTypeCode(String volumeAllotmentProtocolTypeCode) {
		this.volumeAllotmentProtocolTypeCode = volumeAllotmentProtocolTypeCode;
		return this;
	}

	 /**
	 * 볼륨할당프로토콜유형코드
	 * @return volumeAllotmentProtocolTypeCode
	**/
	public String getVolumeAllotmentProtocolTypeCode() {
		return volumeAllotmentProtocolTypeCode;
	}

	public void setVolumeAllotmentProtocolTypeCode(String volumeAllotmentProtocolTypeCode) {
		this.volumeAllotmentProtocolTypeCode = volumeAllotmentProtocolTypeCode;
	}

	public CreateNasVolumeInstanceRequest serverInstanceNoList(List<String> serverInstanceNoList) {
		this.serverInstanceNoList = serverInstanceNoList;
		return this;
	}

	public CreateNasVolumeInstanceRequest addServerInstanceNoListItem(String serverInstanceNoListItem) {
		if (this.serverInstanceNoList == null) {
			this.serverInstanceNoList = new ArrayList<String>();
		}
		this.serverInstanceNoList.add(serverInstanceNoListItem);
		return this;
	}

	 /**
	 * 서버인스턴스번호리스트
	 * @return serverInstanceNoList
	**/
	public List<String> getServerInstanceNoList() {
		return serverInstanceNoList;
	}

	public void setServerInstanceNoList(List<String> serverInstanceNoList) {
		this.serverInstanceNoList = serverInstanceNoList;
	}

	public CreateNasVolumeInstanceRequest customIpList(List<String> customIpList) {
		this.customIpList = customIpList;
		return this;
	}

	public CreateNasVolumeInstanceRequest addCustomIpListItem(String customIpListItem) {
		if (this.customIpList == null) {
			this.customIpList = new ArrayList<String>();
		}
		this.customIpList.add(customIpListItem);
		return this;
	}

	 /**
	 * 커스텀IP리스트
	 * @return customIpList
	**/
	public List<String> getCustomIpList() {
		return customIpList;
	}

	public void setCustomIpList(List<String> customIpList) {
		this.customIpList = customIpList;
	}

	public CreateNasVolumeInstanceRequest cifsUserName(String cifsUserName) {
		this.cifsUserName = cifsUserName;
		return this;
	}

	 /**
	 * CIFS유저이름
	 * @return cifsUserName
	**/
	public String getCifsUserName() {
		return cifsUserName;
	}

	public void setCifsUserName(String cifsUserName) {
		this.cifsUserName = cifsUserName;
	}

	public CreateNasVolumeInstanceRequest cifsUserPassword(String cifsUserPassword) {
		this.cifsUserPassword = cifsUserPassword;
		return this;
	}

	 /**
	 * CIFS유저비밀번호
	 * @return cifsUserPassword
	**/
	public String getCifsUserPassword() {
		return cifsUserPassword;
	}

	public void setCifsUserPassword(String cifsUserPassword) {
		this.cifsUserPassword = cifsUserPassword;
	}

	public CreateNasVolumeInstanceRequest nasVolumeDescription(String nasVolumeDescription) {
		this.nasVolumeDescription = nasVolumeDescription;
		return this;
	}

	 /**
	 * NAS볼륨설명
	 * @return nasVolumeDescription
	**/
	public String getNasVolumeDescription() {
		return nasVolumeDescription;
	}

	public void setNasVolumeDescription(String nasVolumeDescription) {
		this.nasVolumeDescription = nasVolumeDescription;
	}

	public CreateNasVolumeInstanceRequest regionNo(String regionNo) {
		this.regionNo = regionNo;
		return this;
	}

	 /**
	 * 리전번호
	 * @return regionNo
	**/
	public String getRegionNo() {
		return regionNo;
	}

	public void setRegionNo(String regionNo) {
		this.regionNo = regionNo;
	}

	public CreateNasVolumeInstanceRequest zoneNo(String zoneNo) {
		this.zoneNo = zoneNo;
		return this;
	}

	 /**
	 * ZONE번호
	 * @return zoneNo
	**/
	public String getZoneNo() {
		return zoneNo;
	}

	public void setZoneNo(String zoneNo) {
		this.zoneNo = zoneNo;
	}

	public CreateNasVolumeInstanceRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CreateNasVolumeInstanceRequest createNasVolumeInstanceRequest = (CreateNasVolumeInstanceRequest) o;
		return Objects.equals(this.volumeName, createNasVolumeInstanceRequest.volumeName) &&
				Objects.equals(this.volumeSize, createNasVolumeInstanceRequest.volumeSize) &&
				Objects.equals(this.volumeAllotmentProtocolTypeCode, createNasVolumeInstanceRequest.volumeAllotmentProtocolTypeCode) &&
				Objects.equals(this.serverInstanceNoList, createNasVolumeInstanceRequest.serverInstanceNoList) &&
				Objects.equals(this.customIpList, createNasVolumeInstanceRequest.customIpList) &&
				Objects.equals(this.cifsUserName, createNasVolumeInstanceRequest.cifsUserName) &&
				Objects.equals(this.cifsUserPassword, createNasVolumeInstanceRequest.cifsUserPassword) &&
				Objects.equals(this.nasVolumeDescription, createNasVolumeInstanceRequest.nasVolumeDescription) &&
				Objects.equals(this.regionNo, createNasVolumeInstanceRequest.regionNo) &&
				Objects.equals(this.zoneNo, createNasVolumeInstanceRequest.zoneNo) &&
				Objects.equals(this.responseFormatType, createNasVolumeInstanceRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(volumeName, volumeSize, volumeAllotmentProtocolTypeCode, serverInstanceNoList, customIpList, cifsUserName, cifsUserPassword, nasVolumeDescription, regionNo, zoneNo, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CreateNasVolumeInstanceRequest {\n");
		
		sb.append("		volumeName: ").append(toIndentedString(volumeName)).append("\n");
		sb.append("		volumeSize: ").append(toIndentedString(volumeSize)).append("\n");
		sb.append("		volumeAllotmentProtocolTypeCode: ").append(toIndentedString(volumeAllotmentProtocolTypeCode)).append("\n");
		sb.append("		serverInstanceNoList: ").append(toIndentedString(serverInstanceNoList)).append("\n");
		sb.append("		customIpList: ").append(toIndentedString(customIpList)).append("\n");
		sb.append("		cifsUserName: ").append(toIndentedString(cifsUserName)).append("\n");
		sb.append("		cifsUserPassword: ").append(toIndentedString(cifsUserPassword)).append("\n");
		sb.append("		nasVolumeDescription: ").append(toIndentedString(nasVolumeDescription)).append("\n");
		sb.append("		regionNo: ").append(toIndentedString(regionNo)).append("\n");
		sb.append("		zoneNo: ").append(toIndentedString(zoneNo)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

