/*
 * server
 * <br/>https://ncloud.apigw.ntruss.com/server/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.server.model;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * GetInstanceTagListRequest
 */
public class GetInstanceTagListRequest {
	private List<String> instanceNoList = null;

	private List<String> tagKeyList = null;

	private List<String> tagValueList = null;

	private Integer pageNo = null;

	private Integer pageSize = null;

	private String responseFormatType = null;

	public GetInstanceTagListRequest instanceNoList(List<String> instanceNoList) {
		this.instanceNoList = instanceNoList;
		return this;
	}

	public GetInstanceTagListRequest addInstanceNoListItem(String instanceNoListItem) {
		if (this.instanceNoList == null) {
			this.instanceNoList = new ArrayList<String>();
		}
		this.instanceNoList.add(instanceNoListItem);
		return this;
	}

	 /**
	 * 인스턴스번호리스트
	 * @return instanceNoList
	**/
	public List<String> getInstanceNoList() {
		return instanceNoList;
	}

	public void setInstanceNoList(List<String> instanceNoList) {
		this.instanceNoList = instanceNoList;
	}

	public GetInstanceTagListRequest tagKeyList(List<String> tagKeyList) {
		this.tagKeyList = tagKeyList;
		return this;
	}

	public GetInstanceTagListRequest addTagKeyListItem(String tagKeyListItem) {
		if (this.tagKeyList == null) {
			this.tagKeyList = new ArrayList<String>();
		}
		this.tagKeyList.add(tagKeyListItem);
		return this;
	}

	 /**
	 * 태그키리스트
	 * @return tagKeyList
	**/
	public List<String> getTagKeyList() {
		return tagKeyList;
	}

	public void setTagKeyList(List<String> tagKeyList) {
		this.tagKeyList = tagKeyList;
	}

	public GetInstanceTagListRequest tagValueList(List<String> tagValueList) {
		this.tagValueList = tagValueList;
		return this;
	}

	public GetInstanceTagListRequest addTagValueListItem(String tagValueListItem) {
		if (this.tagValueList == null) {
			this.tagValueList = new ArrayList<String>();
		}
		this.tagValueList.add(tagValueListItem);
		return this;
	}

	 /**
	 * 태그값리스트
	 * @return tagValueList
	**/
	public List<String> getTagValueList() {
		return tagValueList;
	}

	public void setTagValueList(List<String> tagValueList) {
		this.tagValueList = tagValueList;
	}

	public GetInstanceTagListRequest pageNo(Integer pageNo) {
		this.pageNo = pageNo;
		return this;
	}

	 /**
	 * 페이지번호
	 * @return pageNo
	**/
	public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public GetInstanceTagListRequest pageSize(Integer pageSize) {
		this.pageSize = pageSize;
		return this;
	}

	 /**
	 * 페이지사이즈
	 * @return pageSize
	**/
	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public GetInstanceTagListRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetInstanceTagListRequest getInstanceTagListRequest = (GetInstanceTagListRequest) o;
		return Objects.equals(this.instanceNoList, getInstanceTagListRequest.instanceNoList) &&
				Objects.equals(this.tagKeyList, getInstanceTagListRequest.tagKeyList) &&
				Objects.equals(this.tagValueList, getInstanceTagListRequest.tagValueList) &&
				Objects.equals(this.pageNo, getInstanceTagListRequest.pageNo) &&
				Objects.equals(this.pageSize, getInstanceTagListRequest.pageSize) &&
				Objects.equals(this.responseFormatType, getInstanceTagListRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(instanceNoList, tagKeyList, tagValueList, pageNo, pageSize, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetInstanceTagListRequest {\n");
		
		sb.append("		instanceNoList: ").append(toIndentedString(instanceNoList)).append("\n");
		sb.append("		tagKeyList: ").append(toIndentedString(tagKeyList)).append("\n");
		sb.append("		tagValueList: ").append(toIndentedString(tagValueList)).append("\n");
		sb.append("		pageNo: ").append(toIndentedString(pageNo)).append("\n");
		sb.append("		pageSize: ").append(toIndentedString(pageSize)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

