/*
 * server
 * <br/>https://ncloud.apigw.ntruss.com/server/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.server.model;

import java.util.Objects;

/**
 * NasVolumeSnapshot
 */
public class NasVolumeSnapshot {
	private String nasVolumeSnapshotName = null;

	private String createDate = null;

	private Long snapshotSize = null;

	private Boolean isBusy = null;

	public NasVolumeSnapshot nasVolumeSnapshotName(String nasVolumeSnapshotName) {
		this.nasVolumeSnapshotName = nasVolumeSnapshotName;
		return this;
	}

	 /**
	 * NAS볼륨스냅샷이름
	 * @return nasVolumeSnapshotName
	**/
	public String getNasVolumeSnapshotName() {
		return nasVolumeSnapshotName;
	}

	public void setNasVolumeSnapshotName(String nasVolumeSnapshotName) {
		this.nasVolumeSnapshotName = nasVolumeSnapshotName;
	}

	public NasVolumeSnapshot createDate(String createDate) {
		this.createDate = createDate;
		return this;
	}

	 /**
	 * 생성일시
	 * @return createDate
	**/
	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public NasVolumeSnapshot snapshotSize(Long snapshotSize) {
		this.snapshotSize = snapshotSize;
		return this;
	}

	 /**
	 * 스냡샷사이즈
	 * @return snapshotSize
	**/
	public Long getSnapshotSize() {
		return snapshotSize;
	}

	public void setSnapshotSize(Long snapshotSize) {
		this.snapshotSize = snapshotSize;
	}

	public NasVolumeSnapshot isBusy(Boolean isBusy) {
		this.isBusy = isBusy;
		return this;
	}

	 /**
	 * busy여부
	 * @return isBusy
	**/
	public Boolean isIsBusy() {
		return isBusy;
	}

	public void setIsBusy(Boolean isBusy) {
		this.isBusy = isBusy;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		NasVolumeSnapshot nasVolumeSnapshot = (NasVolumeSnapshot) o;
		return Objects.equals(this.nasVolumeSnapshotName, nasVolumeSnapshot.nasVolumeSnapshotName) &&
				Objects.equals(this.createDate, nasVolumeSnapshot.createDate) &&
				Objects.equals(this.snapshotSize, nasVolumeSnapshot.snapshotSize) &&
				Objects.equals(this.isBusy, nasVolumeSnapshot.isBusy);
	}

	@Override
	public int hashCode() {
		return Objects.hash(nasVolumeSnapshotName, createDate, snapshotSize, isBusy);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class NasVolumeSnapshot {\n");
		
		sb.append("		nasVolumeSnapshotName: ").append(toIndentedString(nasVolumeSnapshotName)).append("\n");
		sb.append("		createDate: ").append(toIndentedString(createDate)).append("\n");
		sb.append("		snapshotSize: ").append(toIndentedString(snapshotSize)).append("\n");
		sb.append("		isBusy: ").append(toIndentedString(isBusy)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

