/*
 * server
 * <br/>https://ncloud.apigw.ntruss.com/server/v2
 *
 * OpenAPI spec version: 2019-10-17T10:28:43Z
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.server.model;

import java.util.Objects;
import com.ncloud.server.model.ServerInstance;

/**
 * PortForwardingRule
 */
public class PortForwardingRule {
	private Integer portForwardingExternalPort = null;

	private Integer portForwardingInternalPort = null;

	private ServerInstance serverInstance = null;

	public PortForwardingRule portForwardingExternalPort(Integer portForwardingExternalPort) {
		this.portForwardingExternalPort = portForwardingExternalPort;
		return this;
	}

	 /**
	 * 포트포워딩외부포트
	 * @return portForwardingExternalPort
	**/
	public Integer getPortForwardingExternalPort() {
		return portForwardingExternalPort;
	}

	public void setPortForwardingExternalPort(Integer portForwardingExternalPort) {
		this.portForwardingExternalPort = portForwardingExternalPort;
	}

	public PortForwardingRule portForwardingInternalPort(Integer portForwardingInternalPort) {
		this.portForwardingInternalPort = portForwardingInternalPort;
		return this;
	}

	 /**
	 * 포트포워딩내부포트
	 * @return portForwardingInternalPort
	**/
	public Integer getPortForwardingInternalPort() {
		return portForwardingInternalPort;
	}

	public void setPortForwardingInternalPort(Integer portForwardingInternalPort) {
		this.portForwardingInternalPort = portForwardingInternalPort;
	}

	public PortForwardingRule serverInstance(ServerInstance serverInstance) {
		this.serverInstance = serverInstance;
		return this;
	}

	 /**
	 * 서버인스턴스
	 * @return serverInstance
	**/
	public ServerInstance getServerInstance() {
		return serverInstance;
	}

	public void setServerInstance(ServerInstance serverInstance) {
		this.serverInstance = serverInstance;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PortForwardingRule portForwardingRule = (PortForwardingRule) o;
		return Objects.equals(this.portForwardingExternalPort, portForwardingRule.portForwardingExternalPort) &&
				Objects.equals(this.portForwardingInternalPort, portForwardingRule.portForwardingInternalPort) &&
				Objects.equals(this.serverInstance, portForwardingRule.serverInstance);
	}

	@Override
	public int hashCode() {
		return Objects.hash(portForwardingExternalPort, portForwardingInternalPort, serverInstance);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PortForwardingRule {\n");
		
		sb.append("		portForwardingExternalPort: ").append(toIndentedString(portForwardingExternalPort)).append("\n");
		sb.append("		portForwardingInternalPort: ").append(toIndentedString(portForwardingInternalPort)).append("\n");
		sb.append("		serverInstance: ").append(toIndentedString(serverInstance)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

