/*
 * server
 * <br/>https://ncloud.apigw.ntruss.com/server/v2
 *
 * OpenAPI spec version: 2020-09-09T12:03:56Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.server.model;

import java.util.Objects;

/**
 * Raid
 */
public class Raid {
	private String raidTypeName = null;

	private String raidName = null;

	public Raid raidTypeName(String raidTypeName) {
		this.raidTypeName = raidTypeName;
		return this;
	}

	 /**
	 * RAID구분이름
	 * @return raidTypeName
	**/
	public String getRaidTypeName() {
		return raidTypeName;
	}

	public void setRaidTypeName(String raidTypeName) {
		this.raidTypeName = raidTypeName;
	}

	public Raid raidName(String raidName) {
		this.raidName = raidName;
		return this;
	}

	 /**
	 * RAID이름
	 * @return raidName
	**/
	public String getRaidName() {
		return raidName;
	}

	public void setRaidName(String raidName) {
		this.raidName = raidName;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Raid raid = (Raid) o;
		return Objects.equals(this.raidTypeName, raid.raidTypeName) &&
				Objects.equals(this.raidName, raid.raidName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(raidTypeName, raidName);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Raid {\n");
		
		sb.append("		raidTypeName: ").append(toIndentedString(raidTypeName)).append("\n");
		sb.append("		raidName: ").append(toIndentedString(raidName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

