/*
 * autoscaling
 * <br/>https://ncloud.apigw.ntruss.com/autoscaling/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.autoscaling.model;

import java.util.Objects;
import com.ncloud.autoscaling.model.ConfigurationLog;
import java.util.ArrayList;
import java.util.List;

/**
 * GetAutoScalingConfigurationLogListResponse
 */
public class GetAutoScalingConfigurationLogListResponse {
	private String requestId = null;

	private String returnCode = null;

	private String returnMessage = null;

	private Integer totalRows = null;

	private List<ConfigurationLog> configurationLogList = null;

	public GetAutoScalingConfigurationLogListResponse requestId(String requestId) {
		this.requestId = requestId;
		return this;
	}

	 /**
	 * Get requestId
	 * @return requestId
	**/
	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public GetAutoScalingConfigurationLogListResponse returnCode(String returnCode) {
		this.returnCode = returnCode;
		return this;
	}

	 /**
	 * Get returnCode
	 * @return returnCode
	**/
	public String getReturnCode() {
		return returnCode;
	}

	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	public GetAutoScalingConfigurationLogListResponse returnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
		return this;
	}

	 /**
	 * Get returnMessage
	 * @return returnMessage
	**/
	public String getReturnMessage() {
		return returnMessage;
	}

	public void setReturnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
	}

	public GetAutoScalingConfigurationLogListResponse totalRows(Integer totalRows) {
		this.totalRows = totalRows;
		return this;
	}

	 /**
	 * Get totalRows
	 * @return totalRows
	**/
	public Integer getTotalRows() {
		return totalRows;
	}

	public void setTotalRows(Integer totalRows) {
		this.totalRows = totalRows;
	}

	public GetAutoScalingConfigurationLogListResponse configurationLogList(List<ConfigurationLog> configurationLogList) {
		this.configurationLogList = configurationLogList;
		return this;
	}

	public GetAutoScalingConfigurationLogListResponse addConfigurationLogListItem(ConfigurationLog configurationLogListItem) {
		if (this.configurationLogList == null) {
			this.configurationLogList = new ArrayList<ConfigurationLog>();
		}
		this.configurationLogList.add(configurationLogListItem);
		return this;
	}

	 /**
	 * Get configurationLogList
	 * @return configurationLogList
	**/
	public List<ConfigurationLog> getConfigurationLogList() {
		return configurationLogList;
	}

	public void setConfigurationLogList(List<ConfigurationLog> configurationLogList) {
		this.configurationLogList = configurationLogList;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetAutoScalingConfigurationLogListResponse getAutoScalingConfigurationLogListResponse = (GetAutoScalingConfigurationLogListResponse) o;
		return Objects.equals(this.requestId, getAutoScalingConfigurationLogListResponse.requestId) &&
				Objects.equals(this.returnCode, getAutoScalingConfigurationLogListResponse.returnCode) &&
				Objects.equals(this.returnMessage, getAutoScalingConfigurationLogListResponse.returnMessage) &&
				Objects.equals(this.totalRows, getAutoScalingConfigurationLogListResponse.totalRows) &&
				Objects.equals(this.configurationLogList, getAutoScalingConfigurationLogListResponse.configurationLogList);
	}

	@Override
	public int hashCode() {
		return Objects.hash(requestId, returnCode, returnMessage, totalRows, configurationLogList);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetAutoScalingConfigurationLogListResponse {\n");
		
		sb.append("		requestId: ").append(toIndentedString(requestId)).append("\n");
		sb.append("		returnCode: ").append(toIndentedString(returnCode)).append("\n");
		sb.append("		returnMessage: ").append(toIndentedString(returnMessage)).append("\n");
		sb.append("		totalRows: ").append(toIndentedString(totalRows)).append("\n");
		sb.append("		configurationLogList: ").append(toIndentedString(configurationLogList)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

