/*
 * autoscaling
 * <br/>https://ncloud.apigw.ntruss.com/autoscaling/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.autoscaling.model;

import java.util.Objects;
import com.ncloud.autoscaling.model.CommonCode;

/**
 * Process
 */
public class Process {
	private CommonCode process = null;

	public Process process(CommonCode process) {
		this.process = process;
		return this;
	}

	 /**
	 * Get process
	 * @return process
	**/
	public CommonCode getProcess() {
		return process;
	}

	public void setProcess(CommonCode process) {
		this.process = process;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Process process = (Process) o;
		return Objects.equals(this.process, process.process);
	}

	@Override
	public int hashCode() {
		return Objects.hash(process);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Process {\n");
		
		sb.append("		process: ").append(toIndentedString(process)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

