/*
 * autoscaling
 * <br/>https://ncloud.apigw.ntruss.com/autoscaling/v2
 *
 * OpenAPI spec version: 2018-11-13T06:27:22Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.autoscaling.model;

import java.util.Objects;

/**
 * PutScheduledUpdateGroupActionRequest
 */
public class PutScheduledUpdateGroupActionRequest {
	private String autoScalingGroupName = null;

	private Integer desiredCapacity = null;

	private String endTime = null;

	private Integer maxSize = null;

	private Integer minSize = null;

	private String recurrenceInKST = null;

	private String scheduledActionName = null;

	private String startTime = null;

	private String responseFormatType = null;

	public PutScheduledUpdateGroupActionRequest autoScalingGroupName(String autoScalingGroupName) {
		this.autoScalingGroupName = autoScalingGroupName;
		return this;
	}

	 /**
	 * 오토스케일링그룹명
	 * @return autoScalingGroupName
	**/
	public String getAutoScalingGroupName() {
		return autoScalingGroupName;
	}

	public void setAutoScalingGroupName(String autoScalingGroupName) {
		this.autoScalingGroupName = autoScalingGroupName;
	}

	public PutScheduledUpdateGroupActionRequest desiredCapacity(Integer desiredCapacity) {
		this.desiredCapacity = desiredCapacity;
		return this;
	}

	 /**
	 * 기대용량치
	 * @return desiredCapacity
	**/
	public Integer getDesiredCapacity() {
		return desiredCapacity;
	}

	public void setDesiredCapacity(Integer desiredCapacity) {
		this.desiredCapacity = desiredCapacity;
	}

	public PutScheduledUpdateGroupActionRequest endTime(String endTime) {
		this.endTime = endTime;
		return this;
	}

	 /**
	 * 반복스케쥴종료시간
	 * @return endTime
	**/
	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public PutScheduledUpdateGroupActionRequest maxSize(Integer maxSize) {
		this.maxSize = maxSize;
		return this;
	}

	 /**
	 * 최대사이즈
	 * @return maxSize
	**/
	public Integer getMaxSize() {
		return maxSize;
	}

	public void setMaxSize(Integer maxSize) {
		this.maxSize = maxSize;
	}

	public PutScheduledUpdateGroupActionRequest minSize(Integer minSize) {
		this.minSize = minSize;
		return this;
	}

	 /**
	 * 최소사이즈
	 * @return minSize
	**/
	public Integer getMinSize() {
		return minSize;
	}

	public void setMinSize(Integer minSize) {
		this.minSize = minSize;
	}

	public PutScheduledUpdateGroupActionRequest recurrenceInKST(String recurrenceInKST) {
		this.recurrenceInKST = recurrenceInKST;
		return this;
	}

	 /**
	 * 반복스케줄설정
	 * @return recurrenceInKST
	**/
	public String getRecurrenceInKST() {
		return recurrenceInKST;
	}

	public void setRecurrenceInKST(String recurrenceInKST) {
		this.recurrenceInKST = recurrenceInKST;
	}

	public PutScheduledUpdateGroupActionRequest scheduledActionName(String scheduledActionName) {
		this.scheduledActionName = scheduledActionName;
		return this;
	}

	 /**
	 * 스케쥴액션명
	 * @return scheduledActionName
	**/
	public String getScheduledActionName() {
		return scheduledActionName;
	}

	public void setScheduledActionName(String scheduledActionName) {
		this.scheduledActionName = scheduledActionName;
	}

	public PutScheduledUpdateGroupActionRequest startTime(String startTime) {
		this.startTime = startTime;
		return this;
	}

	 /**
	 * 스케쥴시작시간
	 * @return startTime
	**/
	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public PutScheduledUpdateGroupActionRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PutScheduledUpdateGroupActionRequest putScheduledUpdateGroupActionRequest = (PutScheduledUpdateGroupActionRequest) o;
		return Objects.equals(this.autoScalingGroupName, putScheduledUpdateGroupActionRequest.autoScalingGroupName) &&
				Objects.equals(this.desiredCapacity, putScheduledUpdateGroupActionRequest.desiredCapacity) &&
				Objects.equals(this.endTime, putScheduledUpdateGroupActionRequest.endTime) &&
				Objects.equals(this.maxSize, putScheduledUpdateGroupActionRequest.maxSize) &&
				Objects.equals(this.minSize, putScheduledUpdateGroupActionRequest.minSize) &&
				Objects.equals(this.recurrenceInKST, putScheduledUpdateGroupActionRequest.recurrenceInKST) &&
				Objects.equals(this.scheduledActionName, putScheduledUpdateGroupActionRequest.scheduledActionName) &&
				Objects.equals(this.startTime, putScheduledUpdateGroupActionRequest.startTime) &&
				Objects.equals(this.responseFormatType, putScheduledUpdateGroupActionRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(autoScalingGroupName, desiredCapacity, endTime, maxSize, minSize, recurrenceInKST, scheduledActionName, startTime, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PutScheduledUpdateGroupActionRequest {\n");
		
		sb.append("		autoScalingGroupName: ").append(toIndentedString(autoScalingGroupName)).append("\n");
		sb.append("		desiredCapacity: ").append(toIndentedString(desiredCapacity)).append("\n");
		sb.append("		endTime: ").append(toIndentedString(endTime)).append("\n");
		sb.append("		maxSize: ").append(toIndentedString(maxSize)).append("\n");
		sb.append("		minSize: ").append(toIndentedString(minSize)).append("\n");
		sb.append("		recurrenceInKST: ").append(toIndentedString(recurrenceInKST)).append("\n");
		sb.append("		scheduledActionName: ").append(toIndentedString(scheduledActionName)).append("\n");
		sb.append("		startTime: ").append(toIndentedString(startTime)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

