/*
 * autoscaling
 * <br/>https://ncloud.apigw.ntruss.com/autoscaling/v2
 *
 * OpenAPI spec version: 2018-11-13T06:27:22Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.autoscaling.model;

import java.util.Objects;

/**
 * PutScalingPolicyRequest
 */
public class PutScalingPolicyRequest {
	private String adjustmentTypeCode = null;

	private String autoScalingGroupName = null;

	private Integer cooldown = null;

	private Integer minAdjustmentStep = null;

	private String policyName = null;

	private Integer scalingAdjustment = null;

	private String responseFormatType = null;

	public PutScalingPolicyRequest adjustmentTypeCode(String adjustmentTypeCode) {
		this.adjustmentTypeCode = adjustmentTypeCode;
		return this;
	}

	 /**
	 * 조정유형코드
	 * @return adjustmentTypeCode
	**/
	public String getAdjustmentTypeCode() {
		return adjustmentTypeCode;
	}

	public void setAdjustmentTypeCode(String adjustmentTypeCode) {
		this.adjustmentTypeCode = adjustmentTypeCode;
	}

	public PutScalingPolicyRequest autoScalingGroupName(String autoScalingGroupName) {
		this.autoScalingGroupName = autoScalingGroupName;
		return this;
	}

	 /**
	 * 오토스케일링그룹명
	 * @return autoScalingGroupName
	**/
	public String getAutoScalingGroupName() {
		return autoScalingGroupName;
	}

	public void setAutoScalingGroupName(String autoScalingGroupName) {
		this.autoScalingGroupName = autoScalingGroupName;
	}

	public PutScalingPolicyRequest cooldown(Integer cooldown) {
		this.cooldown = cooldown;
		return this;
	}

	 /**
	 * 쿨다운타임
	 * @return cooldown
	**/
	public Integer getCooldown() {
		return cooldown;
	}

	public void setCooldown(Integer cooldown) {
		this.cooldown = cooldown;
	}

	public PutScalingPolicyRequest minAdjustmentStep(Integer minAdjustmentStep) {
		this.minAdjustmentStep = minAdjustmentStep;
		return this;
	}

	 /**
	 * 최소조정스텝
	 * @return minAdjustmentStep
	**/
	public Integer getMinAdjustmentStep() {
		return minAdjustmentStep;
	}

	public void setMinAdjustmentStep(Integer minAdjustmentStep) {
		this.minAdjustmentStep = minAdjustmentStep;
	}

	public PutScalingPolicyRequest policyName(String policyName) {
		this.policyName = policyName;
		return this;
	}

	 /**
	 * 정책명
	 * @return policyName
	**/
	public String getPolicyName() {
		return policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	public PutScalingPolicyRequest scalingAdjustment(Integer scalingAdjustment) {
		this.scalingAdjustment = scalingAdjustment;
		return this;
	}

	 /**
	 * 스케일링조정값
	 * @return scalingAdjustment
	**/
	public Integer getScalingAdjustment() {
		return scalingAdjustment;
	}

	public void setScalingAdjustment(Integer scalingAdjustment) {
		this.scalingAdjustment = scalingAdjustment;
	}

	public PutScalingPolicyRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PutScalingPolicyRequest putScalingPolicyRequest = (PutScalingPolicyRequest) o;
		return Objects.equals(this.adjustmentTypeCode, putScalingPolicyRequest.adjustmentTypeCode) &&
				Objects.equals(this.autoScalingGroupName, putScalingPolicyRequest.autoScalingGroupName) &&
				Objects.equals(this.cooldown, putScalingPolicyRequest.cooldown) &&
				Objects.equals(this.minAdjustmentStep, putScalingPolicyRequest.minAdjustmentStep) &&
				Objects.equals(this.policyName, putScalingPolicyRequest.policyName) &&
				Objects.equals(this.scalingAdjustment, putScalingPolicyRequest.scalingAdjustment) &&
				Objects.equals(this.responseFormatType, putScalingPolicyRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(adjustmentTypeCode, autoScalingGroupName, cooldown, minAdjustmentStep, policyName, scalingAdjustment, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PutScalingPolicyRequest {\n");
		
		sb.append("		adjustmentTypeCode: ").append(toIndentedString(adjustmentTypeCode)).append("\n");
		sb.append("		autoScalingGroupName: ").append(toIndentedString(autoScalingGroupName)).append("\n");
		sb.append("		cooldown: ").append(toIndentedString(cooldown)).append("\n");
		sb.append("		minAdjustmentStep: ").append(toIndentedString(minAdjustmentStep)).append("\n");
		sb.append("		policyName: ").append(toIndentedString(policyName)).append("\n");
		sb.append("		scalingAdjustment: ").append(toIndentedString(scalingAdjustment)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

