/*
 * vserver
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vserver.model;

import java.util.Objects;
import com.ncloud.vserver.model.CommonCode;

/**
 * AccessControlGroupRule
 */
public class AccessControlGroupRule {
	private String accessControlGroupNo = null;

	private CommonCode protocolType = null;

	private String ipBlock = null;

	private String portRange = null;

	private String accessControlGroupSequence = null;

	private CommonCode accessControlGroupRuleType = null;

	private String accessControlGroupRuleDescription = null;

	public AccessControlGroupRule accessControlGroupNo(String accessControlGroupNo) {
		this.accessControlGroupNo = accessControlGroupNo;
		return this;
	}

	 /**
	 * ACG번호
	 * @return accessControlGroupNo
	**/
	public String getAccessControlGroupNo() {
		return accessControlGroupNo;
	}

	public void setAccessControlGroupNo(String accessControlGroupNo) {
		this.accessControlGroupNo = accessControlGroupNo;
	}

	public AccessControlGroupRule protocolType(CommonCode protocolType) {
		this.protocolType = protocolType;
		return this;
	}

	 /**
	 * 프로토콜유형
	 * @return protocolType
	**/
	public CommonCode getProtocolType() {
		return protocolType;
	}

	public void setProtocolType(CommonCode protocolType) {
		this.protocolType = protocolType;
	}

	public AccessControlGroupRule ipBlock(String ipBlock) {
		this.ipBlock = ipBlock;
		return this;
	}

	 /**
	 * IP블록
	 * @return ipBlock
	**/
	public String getIpBlock() {
		return ipBlock;
	}

	public void setIpBlock(String ipBlock) {
		this.ipBlock = ipBlock;
	}

	public AccessControlGroupRule portRange(String portRange) {
		this.portRange = portRange;
		return this;
	}

	 /**
	 * 포트범위
	 * @return portRange
	**/
	public String getPortRange() {
		return portRange;
	}

	public void setPortRange(String portRange) {
		this.portRange = portRange;
	}

	public AccessControlGroupRule accessControlGroupSequence(String accessControlGroupSequence) {
		this.accessControlGroupSequence = accessControlGroupSequence;
		return this;
	}

	 /**
	 * 접근소스ACG
	 * @return accessControlGroupSequence
	**/
	public String getAccessControlGroupSequence() {
		return accessControlGroupSequence;
	}

	public void setAccessControlGroupSequence(String accessControlGroupSequence) {
		this.accessControlGroupSequence = accessControlGroupSequence;
	}

	public AccessControlGroupRule accessControlGroupRuleType(CommonCode accessControlGroupRuleType) {
		this.accessControlGroupRuleType = accessControlGroupRuleType;
		return this;
	}

	 /**
	 * ACGRule유형
	 * @return accessControlGroupRuleType
	**/
	public CommonCode getAccessControlGroupRuleType() {
		return accessControlGroupRuleType;
	}

	public void setAccessControlGroupRuleType(CommonCode accessControlGroupRuleType) {
		this.accessControlGroupRuleType = accessControlGroupRuleType;
	}

	public AccessControlGroupRule accessControlGroupRuleDescription(String accessControlGroupRuleDescription) {
		this.accessControlGroupRuleDescription = accessControlGroupRuleDescription;
		return this;
	}

	 /**
	 * ACGRule설명
	 * @return accessControlGroupRuleDescription
	**/
	public String getAccessControlGroupRuleDescription() {
		return accessControlGroupRuleDescription;
	}

	public void setAccessControlGroupRuleDescription(String accessControlGroupRuleDescription) {
		this.accessControlGroupRuleDescription = accessControlGroupRuleDescription;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AccessControlGroupRule accessControlGroupRule = (AccessControlGroupRule) o;
		return Objects.equals(this.accessControlGroupNo, accessControlGroupRule.accessControlGroupNo) &&
				Objects.equals(this.protocolType, accessControlGroupRule.protocolType) &&
				Objects.equals(this.ipBlock, accessControlGroupRule.ipBlock) &&
				Objects.equals(this.portRange, accessControlGroupRule.portRange) &&
				Objects.equals(this.accessControlGroupSequence, accessControlGroupRule.accessControlGroupSequence) &&
				Objects.equals(this.accessControlGroupRuleType, accessControlGroupRule.accessControlGroupRuleType) &&
				Objects.equals(this.accessControlGroupRuleDescription, accessControlGroupRule.accessControlGroupRuleDescription);
	}

	@Override
	public int hashCode() {
		return Objects.hash(accessControlGroupNo, protocolType, ipBlock, portRange, accessControlGroupSequence, accessControlGroupRuleType, accessControlGroupRuleDescription);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AccessControlGroupRule {\n");
		
		sb.append("		accessControlGroupNo: ").append(toIndentedString(accessControlGroupNo)).append("\n");
		sb.append("		protocolType: ").append(toIndentedString(protocolType)).append("\n");
		sb.append("		ipBlock: ").append(toIndentedString(ipBlock)).append("\n");
		sb.append("		portRange: ").append(toIndentedString(portRange)).append("\n");
		sb.append("		accessControlGroupSequence: ").append(toIndentedString(accessControlGroupSequence)).append("\n");
		sb.append("		accessControlGroupRuleType: ").append(toIndentedString(accessControlGroupRuleType)).append("\n");
		sb.append("		accessControlGroupRuleDescription: ").append(toIndentedString(accessControlGroupRuleDescription)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

