/*
 * vserver
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vserver.model;

import java.util.Objects;

/**
 * AddAccessControlGroupRuleParameter
 */
public class AddAccessControlGroupRuleParameter {
	private String accessControlGroupRuleDescription = null;

	private String ipBlock = null;

	private String accessControlGroupSequence = null;

	private String portRange = null;

	private String protocolTypeCode = null;

	public AddAccessControlGroupRuleParameter accessControlGroupRuleDescription(String accessControlGroupRuleDescription) {
		this.accessControlGroupRuleDescription = accessControlGroupRuleDescription;
		return this;
	}

	 /**
	 * ACGRule설명
	 * @return accessControlGroupRuleDescription
	**/
	public String getAccessControlGroupRuleDescription() {
		return accessControlGroupRuleDescription;
	}

	public void setAccessControlGroupRuleDescription(String accessControlGroupRuleDescription) {
		this.accessControlGroupRuleDescription = accessControlGroupRuleDescription;
	}

	public AddAccessControlGroupRuleParameter ipBlock(String ipBlock) {
		this.ipBlock = ipBlock;
		return this;
	}

	 /**
	 * IP블록
	 * @return ipBlock
	**/
	public String getIpBlock() {
		return ipBlock;
	}

	public void setIpBlock(String ipBlock) {
		this.ipBlock = ipBlock;
	}

	public AddAccessControlGroupRuleParameter accessControlGroupSequence(String accessControlGroupSequence) {
		this.accessControlGroupSequence = accessControlGroupSequence;
		return this;
	}

	 /**
	 * 접근소스ACG
	 * @return accessControlGroupSequence
	**/
	public String getAccessControlGroupSequence() {
		return accessControlGroupSequence;
	}

	public void setAccessControlGroupSequence(String accessControlGroupSequence) {
		this.accessControlGroupSequence = accessControlGroupSequence;
	}

	public AddAccessControlGroupRuleParameter portRange(String portRange) {
		this.portRange = portRange;
		return this;
	}

	 /**
	 * 포트범위
	 * @return portRange
	**/
	public String getPortRange() {
		return portRange;
	}

	public void setPortRange(String portRange) {
		this.portRange = portRange;
	}

	public AddAccessControlGroupRuleParameter protocolTypeCode(String protocolTypeCode) {
		this.protocolTypeCode = protocolTypeCode;
		return this;
	}

	 /**
	 * 프로토콜유형코드
	 * @return protocolTypeCode
	**/
	public String getProtocolTypeCode() {
		return protocolTypeCode;
	}

	public void setProtocolTypeCode(String protocolTypeCode) {
		this.protocolTypeCode = protocolTypeCode;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AddAccessControlGroupRuleParameter addAccessControlGroupRuleParameter = (AddAccessControlGroupRuleParameter) o;
		return Objects.equals(this.accessControlGroupRuleDescription, addAccessControlGroupRuleParameter.accessControlGroupRuleDescription) &&
				Objects.equals(this.ipBlock, addAccessControlGroupRuleParameter.ipBlock) &&
				Objects.equals(this.accessControlGroupSequence, addAccessControlGroupRuleParameter.accessControlGroupSequence) &&
				Objects.equals(this.portRange, addAccessControlGroupRuleParameter.portRange) &&
				Objects.equals(this.protocolTypeCode, addAccessControlGroupRuleParameter.protocolTypeCode);
	}

	@Override
	public int hashCode() {
		return Objects.hash(accessControlGroupRuleDescription, ipBlock, accessControlGroupSequence, portRange, protocolTypeCode);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AddAccessControlGroupRuleParameter {\n");
		
		sb.append("		accessControlGroupRuleDescription: ").append(toIndentedString(accessControlGroupRuleDescription)).append("\n");
		sb.append("		ipBlock: ").append(toIndentedString(ipBlock)).append("\n");
		sb.append("		accessControlGroupSequence: ").append(toIndentedString(accessControlGroupSequence)).append("\n");
		sb.append("		portRange: ").append(toIndentedString(portRange)).append("\n");
		sb.append("		protocolTypeCode: ").append(toIndentedString(protocolTypeCode)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

