/*
 * vserver
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vserver.model;

import java.util.Objects;

/**
 * ChangeFabricClusterDescriptionRequest
 */
public class ChangeFabricClusterDescriptionRequest {
	private String regionCode = null;

	private String fabricClusterNo = null;

	private String fabricClusterDescription = null;

	private String responseFormatType = null;

	public ChangeFabricClusterDescriptionRequest regionCode(String regionCode) {
		this.regionCode = regionCode;
		return this;
	}

	 /**
	 * REGION코드
	 * @return regionCode
	**/
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public ChangeFabricClusterDescriptionRequest fabricClusterNo(String fabricClusterNo) {
		this.fabricClusterNo = fabricClusterNo;
		return this;
	}

	 /**
	 * Fabric Cluster 번호
	 * @return fabricClusterNo
	**/
	public String getFabricClusterNo() {
		return fabricClusterNo;
	}

	public void setFabricClusterNo(String fabricClusterNo) {
		this.fabricClusterNo = fabricClusterNo;
	}

	public ChangeFabricClusterDescriptionRequest fabricClusterDescription(String fabricClusterDescription) {
		this.fabricClusterDescription = fabricClusterDescription;
		return this;
	}

	 /**
	 * Fabric Cluster 설명
	 * @return fabricClusterDescription
	**/
	public String getFabricClusterDescription() {
		return fabricClusterDescription;
	}

	public void setFabricClusterDescription(String fabricClusterDescription) {
		this.fabricClusterDescription = fabricClusterDescription;
	}

	public ChangeFabricClusterDescriptionRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ChangeFabricClusterDescriptionRequest changeFabricClusterDescriptionRequest = (ChangeFabricClusterDescriptionRequest) o;
		return Objects.equals(this.regionCode, changeFabricClusterDescriptionRequest.regionCode) &&
				Objects.equals(this.fabricClusterNo, changeFabricClusterDescriptionRequest.fabricClusterNo) &&
				Objects.equals(this.fabricClusterDescription, changeFabricClusterDescriptionRequest.fabricClusterDescription) &&
				Objects.equals(this.responseFormatType, changeFabricClusterDescriptionRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(regionCode, fabricClusterNo, fabricClusterDescription, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ChangeFabricClusterDescriptionRequest {\n");
		
		sb.append("		regionCode: ").append(toIndentedString(regionCode)).append("\n");
		sb.append("		fabricClusterNo: ").append(toIndentedString(fabricClusterNo)).append("\n");
		sb.append("		fabricClusterDescription: ").append(toIndentedString(fabricClusterDescription)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

