/*
 * vserver
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vserver.model;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * GetFlowLogConfigurationListRequest
 */
public class GetFlowLogConfigurationListRequest {
	private String regionCode = null;

	private List<String> networkInterfaceNoList = new ArrayList<String>();

	private String responseFormatType = null;

	public GetFlowLogConfigurationListRequest regionCode(String regionCode) {
		this.regionCode = regionCode;
		return this;
	}

	 /**
	 * REGION코드
	 * @return regionCode
	**/
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public GetFlowLogConfigurationListRequest networkInterfaceNoList(List<String> networkInterfaceNoList) {
		this.networkInterfaceNoList = networkInterfaceNoList;
		return this;
	}

	public GetFlowLogConfigurationListRequest addNetworkInterfaceNoListItem(String networkInterfaceNoListItem) {
		this.networkInterfaceNoList.add(networkInterfaceNoListItem);
		return this;
	}

	 /**
	 * 네트워크인터페이스번호리스트
	 * @return networkInterfaceNoList
	**/
	public List<String> getNetworkInterfaceNoList() {
		return networkInterfaceNoList;
	}

	public void setNetworkInterfaceNoList(List<String> networkInterfaceNoList) {
		this.networkInterfaceNoList = networkInterfaceNoList;
	}

	public GetFlowLogConfigurationListRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetFlowLogConfigurationListRequest getFlowLogConfigurationListRequest = (GetFlowLogConfigurationListRequest) o;
		return Objects.equals(this.regionCode, getFlowLogConfigurationListRequest.regionCode) &&
				Objects.equals(this.networkInterfaceNoList, getFlowLogConfigurationListRequest.networkInterfaceNoList) &&
				Objects.equals(this.responseFormatType, getFlowLogConfigurationListRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(regionCode, networkInterfaceNoList, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetFlowLogConfigurationListRequest {\n");
		
		sb.append("		regionCode: ").append(toIndentedString(regionCode)).append("\n");
		sb.append("		networkInterfaceNoList: ").append(toIndentedString(networkInterfaceNoList)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

