/*
 * vserver
 * VPC Compute 관련 API<br/>https://ncloud.apigw.ntruss.com/vserver/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vserver.model;

import java.util.Objects;
import com.ncloud.vserver.model.MemberServerImageInstance;
import java.util.ArrayList;
import java.util.List;

/**
 * SetMemberServerImageSharingPermissionResponse
 */
public class SetMemberServerImageSharingPermissionResponse {
	private String requestId = null;

	private String returnCode = null;

	private String returnMessage = null;

	private Integer totalRows = null;

	private List<MemberServerImageInstance> memberServerImageInstanceList = null;

	public SetMemberServerImageSharingPermissionResponse requestId(String requestId) {
		this.requestId = requestId;
		return this;
	}

	 /**
	 * Get requestId
	 * @return requestId
	**/
	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public SetMemberServerImageSharingPermissionResponse returnCode(String returnCode) {
		this.returnCode = returnCode;
		return this;
	}

	 /**
	 * Get returnCode
	 * @return returnCode
	**/
	public String getReturnCode() {
		return returnCode;
	}

	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	public SetMemberServerImageSharingPermissionResponse returnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
		return this;
	}

	 /**
	 * Get returnMessage
	 * @return returnMessage
	**/
	public String getReturnMessage() {
		return returnMessage;
	}

	public void setReturnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
	}

	public SetMemberServerImageSharingPermissionResponse totalRows(Integer totalRows) {
		this.totalRows = totalRows;
		return this;
	}

	 /**
	 * Get totalRows
	 * @return totalRows
	**/
	public Integer getTotalRows() {
		return totalRows;
	}

	public void setTotalRows(Integer totalRows) {
		this.totalRows = totalRows;
	}

	public SetMemberServerImageSharingPermissionResponse memberServerImageInstanceList(List<MemberServerImageInstance> memberServerImageInstanceList) {
		this.memberServerImageInstanceList = memberServerImageInstanceList;
		return this;
	}

	public SetMemberServerImageSharingPermissionResponse addMemberServerImageInstanceListItem(MemberServerImageInstance memberServerImageInstanceListItem) {
		if (this.memberServerImageInstanceList == null) {
			this.memberServerImageInstanceList = new ArrayList<MemberServerImageInstance>();
		}
		this.memberServerImageInstanceList.add(memberServerImageInstanceListItem);
		return this;
	}

	 /**
	 * Get memberServerImageInstanceList
	 * @return memberServerImageInstanceList
	**/
	public List<MemberServerImageInstance> getMemberServerImageInstanceList() {
		return memberServerImageInstanceList;
	}

	public void setMemberServerImageInstanceList(List<MemberServerImageInstance> memberServerImageInstanceList) {
		this.memberServerImageInstanceList = memberServerImageInstanceList;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SetMemberServerImageSharingPermissionResponse setMemberServerImageSharingPermissionResponse = (SetMemberServerImageSharingPermissionResponse) o;
		return Objects.equals(this.requestId, setMemberServerImageSharingPermissionResponse.requestId) &&
				Objects.equals(this.returnCode, setMemberServerImageSharingPermissionResponse.returnCode) &&
				Objects.equals(this.returnMessage, setMemberServerImageSharingPermissionResponse.returnMessage) &&
				Objects.equals(this.totalRows, setMemberServerImageSharingPermissionResponse.totalRows) &&
				Objects.equals(this.memberServerImageInstanceList, setMemberServerImageSharingPermissionResponse.memberServerImageInstanceList);
	}

	@Override
	public int hashCode() {
		return Objects.hash(requestId, returnCode, returnMessage, totalRows, memberServerImageInstanceList);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SetMemberServerImageSharingPermissionResponse {\n");
		
		sb.append("		requestId: ").append(toIndentedString(requestId)).append("\n");
		sb.append("		returnCode: ").append(toIndentedString(returnCode)).append("\n");
		sb.append("		returnMessage: ").append(toIndentedString(returnMessage)).append("\n");
		sb.append("		totalRows: ").append(toIndentedString(totalRows)).append("\n");
		sb.append("		memberServerImageInstanceList: ").append(toIndentedString(memberServerImageInstanceList)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

