/*
 * vloadbalancer
 * VPC Load Balancer 관련 API<br/>https://ncloud.apigw.ntruss.com/vloadbalancer/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vloadbalancer.model;

import java.util.Objects;

/**
 * LoadBalancerListenerCertificate
 */
public class LoadBalancerListenerCertificate {
	private String sslCertificateNo = null;

	private String memberNo = null;

	private String sslCertificateName = null;

	private String domainAddress = null;

	private String validEndDate = null;

	private Boolean isDefault = null;

	private Integer statusCode = null;

	private String statusName = null;

	public LoadBalancerListenerCertificate sslCertificateNo(String sslCertificateNo) {
		this.sslCertificateNo = sslCertificateNo;
		return this;
	}

	 /**
	 * SSL인증서번호
	 * @return sslCertificateNo
	**/
	public String getSslCertificateNo() {
		return sslCertificateNo;
	}

	public void setSslCertificateNo(String sslCertificateNo) {
		this.sslCertificateNo = sslCertificateNo;
	}

	public LoadBalancerListenerCertificate memberNo(String memberNo) {
		this.memberNo = memberNo;
		return this;
	}

	 /**
	 * 사용자번호
	 * @return memberNo
	**/
	public String getMemberNo() {
		return memberNo;
	}

	public void setMemberNo(String memberNo) {
		this.memberNo = memberNo;
	}

	public LoadBalancerListenerCertificate sslCertificateName(String sslCertificateName) {
		this.sslCertificateName = sslCertificateName;
		return this;
	}

	 /**
	 * SSL인증서이름
	 * @return sslCertificateName
	**/
	public String getSslCertificateName() {
		return sslCertificateName;
	}

	public void setSslCertificateName(String sslCertificateName) {
		this.sslCertificateName = sslCertificateName;
	}

	public LoadBalancerListenerCertificate domainAddress(String domainAddress) {
		this.domainAddress = domainAddress;
		return this;
	}

	 /**
	 * 도메인주소
	 * @return domainAddress
	**/
	public String getDomainAddress() {
		return domainAddress;
	}

	public void setDomainAddress(String domainAddress) {
		this.domainAddress = domainAddress;
	}

	public LoadBalancerListenerCertificate validEndDate(String validEndDate) {
		this.validEndDate = validEndDate;
		return this;
	}

	 /**
	 * 인증종료일
	 * @return validEndDate
	**/
	public String getValidEndDate() {
		return validEndDate;
	}

	public void setValidEndDate(String validEndDate) {
		this.validEndDate = validEndDate;
	}

	public LoadBalancerListenerCertificate isDefault(Boolean isDefault) {
		this.isDefault = isDefault;
		return this;
	}

	 /**
	 * 디폴트여부
	 * @return isDefault
	**/
	public Boolean isIsDefault() {
		return isDefault;
	}

	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	public LoadBalancerListenerCertificate statusCode(Integer statusCode) {
		this.statusCode = statusCode;
		return this;
	}

	 /**
	 * 상태코드
	 * @return statusCode
	**/
	public Integer getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	public LoadBalancerListenerCertificate statusName(String statusName) {
		this.statusName = statusName;
		return this;
	}

	 /**
	 * 상태이름
	 * @return statusName
	**/
	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LoadBalancerListenerCertificate loadBalancerListenerCertificate = (LoadBalancerListenerCertificate) o;
		return Objects.equals(this.sslCertificateNo, loadBalancerListenerCertificate.sslCertificateNo) &&
				Objects.equals(this.memberNo, loadBalancerListenerCertificate.memberNo) &&
				Objects.equals(this.sslCertificateName, loadBalancerListenerCertificate.sslCertificateName) &&
				Objects.equals(this.domainAddress, loadBalancerListenerCertificate.domainAddress) &&
				Objects.equals(this.validEndDate, loadBalancerListenerCertificate.validEndDate) &&
				Objects.equals(this.isDefault, loadBalancerListenerCertificate.isDefault) &&
				Objects.equals(this.statusCode, loadBalancerListenerCertificate.statusCode) &&
				Objects.equals(this.statusName, loadBalancerListenerCertificate.statusName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(sslCertificateNo, memberNo, sslCertificateName, domainAddress, validEndDate, isDefault, statusCode, statusName);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LoadBalancerListenerCertificate {\n");
		
		sb.append("		sslCertificateNo: ").append(toIndentedString(sslCertificateNo)).append("\n");
		sb.append("		memberNo: ").append(toIndentedString(memberNo)).append("\n");
		sb.append("		sslCertificateName: ").append(toIndentedString(sslCertificateName)).append("\n");
		sb.append("		domainAddress: ").append(toIndentedString(domainAddress)).append("\n");
		sb.append("		validEndDate: ").append(toIndentedString(validEndDate)).append("\n");
		sb.append("		isDefault: ").append(toIndentedString(isDefault)).append("\n");
		sb.append("		statusCode: ").append(toIndentedString(statusCode)).append("\n");
		sb.append("		statusName: ").append(toIndentedString(statusName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

