/*
 * vloadbalancer
 * VPC Load Balancer 관련 API<br/>https://ncloud.apigw.ntruss.com/vloadbalancer/v2
 *
 * NBP corp.
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vloadbalancer.model;

import java.util.Objects;
import com.ncloud.vloadbalancer.model.LoadBalancerListenerCertificate;
import java.util.ArrayList;
import java.util.List;

/**
 * RemoveLoadBalancerListenerCertificateResponse
 */
public class RemoveLoadBalancerListenerCertificateResponse {
	private String requestId = null;

	private String returnCode = null;

	private String returnMessage = null;

	private Integer totalRows = null;

	private List<LoadBalancerListenerCertificate> loadBalancerListenerCertificateList = null;

	public RemoveLoadBalancerListenerCertificateResponse requestId(String requestId) {
		this.requestId = requestId;
		return this;
	}

	 /**
	 * Get requestId
	 * @return requestId
	**/
	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public RemoveLoadBalancerListenerCertificateResponse returnCode(String returnCode) {
		this.returnCode = returnCode;
		return this;
	}

	 /**
	 * Get returnCode
	 * @return returnCode
	**/
	public String getReturnCode() {
		return returnCode;
	}

	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	public RemoveLoadBalancerListenerCertificateResponse returnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
		return this;
	}

	 /**
	 * Get returnMessage
	 * @return returnMessage
	**/
	public String getReturnMessage() {
		return returnMessage;
	}

	public void setReturnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
	}

	public RemoveLoadBalancerListenerCertificateResponse totalRows(Integer totalRows) {
		this.totalRows = totalRows;
		return this;
	}

	 /**
	 * Get totalRows
	 * @return totalRows
	**/
	public Integer getTotalRows() {
		return totalRows;
	}

	public void setTotalRows(Integer totalRows) {
		this.totalRows = totalRows;
	}

	public RemoveLoadBalancerListenerCertificateResponse loadBalancerListenerCertificateList(List<LoadBalancerListenerCertificate> loadBalancerListenerCertificateList) {
		this.loadBalancerListenerCertificateList = loadBalancerListenerCertificateList;
		return this;
	}

	public RemoveLoadBalancerListenerCertificateResponse addLoadBalancerListenerCertificateListItem(LoadBalancerListenerCertificate loadBalancerListenerCertificateListItem) {
		if (this.loadBalancerListenerCertificateList == null) {
			this.loadBalancerListenerCertificateList = new ArrayList<LoadBalancerListenerCertificate>();
		}
		this.loadBalancerListenerCertificateList.add(loadBalancerListenerCertificateListItem);
		return this;
	}

	 /**
	 * Get loadBalancerListenerCertificateList
	 * @return loadBalancerListenerCertificateList
	**/
	public List<LoadBalancerListenerCertificate> getLoadBalancerListenerCertificateList() {
		return loadBalancerListenerCertificateList;
	}

	public void setLoadBalancerListenerCertificateList(List<LoadBalancerListenerCertificate> loadBalancerListenerCertificateList) {
		this.loadBalancerListenerCertificateList = loadBalancerListenerCertificateList;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RemoveLoadBalancerListenerCertificateResponse removeLoadBalancerListenerCertificateResponse = (RemoveLoadBalancerListenerCertificateResponse) o;
		return Objects.equals(this.requestId, removeLoadBalancerListenerCertificateResponse.requestId) &&
				Objects.equals(this.returnCode, removeLoadBalancerListenerCertificateResponse.returnCode) &&
				Objects.equals(this.returnMessage, removeLoadBalancerListenerCertificateResponse.returnMessage) &&
				Objects.equals(this.totalRows, removeLoadBalancerListenerCertificateResponse.totalRows) &&
				Objects.equals(this.loadBalancerListenerCertificateList, removeLoadBalancerListenerCertificateResponse.loadBalancerListenerCertificateList);
	}

	@Override
	public int hashCode() {
		return Objects.hash(requestId, returnCode, returnMessage, totalRows, loadBalancerListenerCertificateList);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RemoveLoadBalancerListenerCertificateResponse {\n");
		
		sb.append("		requestId: ").append(toIndentedString(requestId)).append("\n");
		sb.append("		returnCode: ").append(toIndentedString(returnCode)).append("\n");
		sb.append("		returnMessage: ").append(toIndentedString(returnMessage)).append("\n");
		sb.append("		totalRows: ").append(toIndentedString(totalRows)).append("\n");
		sb.append("		loadBalancerListenerCertificateList: ").append(toIndentedString(loadBalancerListenerCertificateList)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

