/*
 * vloadbalancer
 * VPC Load Balancer 관련 API<br/>https://ncloud.apigw.ntruss.com/vloadbalancer/v2
 *
 * OpenAPI spec version: 2020-12-22T09:19:59Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vloadbalancer.model;

import java.util.Objects;
import com.ncloud.vloadbalancer.model.TargetGroupWeight;
import java.util.ArrayList;
import java.util.List;

/**
 * TargetGroupAction
 */
public class TargetGroupAction {
	private List<TargetGroupWeight> targetGroupWeightList = null;

	private Boolean useStickySession = null;

	public TargetGroupAction targetGroupWeightList(List<TargetGroupWeight> targetGroupWeightList) {
		this.targetGroupWeightList = targetGroupWeightList;
		return this;
	}

	public TargetGroupAction addTargetGroupWeightListItem(TargetGroupWeight targetGroupWeightListItem) {
		if (this.targetGroupWeightList == null) {
			this.targetGroupWeightList = new ArrayList<TargetGroupWeight>();
		}
		this.targetGroupWeightList.add(targetGroupWeightListItem);
		return this;
	}

	 /**
	 * 타겟그룹가중치리스트
	 * @return targetGroupWeightList
	**/
	public List<TargetGroupWeight> getTargetGroupWeightList() {
		return targetGroupWeightList;
	}

	public void setTargetGroupWeightList(List<TargetGroupWeight> targetGroupWeightList) {
		this.targetGroupWeightList = targetGroupWeightList;
	}

	public TargetGroupAction useStickySession(Boolean useStickySession) {
		this.useStickySession = useStickySession;
		return this;
	}

	 /**
	 * 세션별접근사용여부
	 * @return useStickySession
	**/
	public Boolean isUseStickySession() {
		return useStickySession;
	}

	public void setUseStickySession(Boolean useStickySession) {
		this.useStickySession = useStickySession;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		TargetGroupAction targetGroupAction = (TargetGroupAction) o;
		return Objects.equals(this.targetGroupWeightList, targetGroupAction.targetGroupWeightList) &&
				Objects.equals(this.useStickySession, targetGroupAction.useStickySession);
	}

	@Override
	public int hashCode() {
		return Objects.hash(targetGroupWeightList, useStickySession);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TargetGroupAction {\n");
		
		sb.append("		targetGroupWeightList: ").append(toIndentedString(targetGroupWeightList)).append("\n");
		sb.append("		useStickySession: ").append(toIndentedString(useStickySession)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

