/*
 * vautoscaling
 * VPC Auto Scaling 관련 API<br/>https://ncloud.apigw.ntruss.com/vautoscaling/v2
 *
 * OpenAPI spec version: 2021-01-21T11:15:08Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vautoscaling.model;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;

/**
 * GetAutoScalingActivityLogListRequest
 */
public class GetAutoScalingActivityLogListRequest {
	private String regionCode = null;

	private String autoScalingGroupNo = null;

	private List<String> activityNoList = null;

	private Integer pageNo = null;

	private Integer pageSize = null;

	private String responseFormatType = null;

	public GetAutoScalingActivityLogListRequest regionCode(String regionCode) {
		this.regionCode = regionCode;
		return this;
	}

	 /**
	 * REGION코드
	 * @return regionCode
	**/
	public String getRegionCode() {
		return regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	public GetAutoScalingActivityLogListRequest autoScalingGroupNo(String autoScalingGroupNo) {
		this.autoScalingGroupNo = autoScalingGroupNo;
		return this;
	}

	 /**
	 * 오토스케일링그룹번호
	 * @return autoScalingGroupNo
	**/
	public String getAutoScalingGroupNo() {
		return autoScalingGroupNo;
	}

	public void setAutoScalingGroupNo(String autoScalingGroupNo) {
		this.autoScalingGroupNo = autoScalingGroupNo;
	}

	public GetAutoScalingActivityLogListRequest activityNoList(List<String> activityNoList) {
		this.activityNoList = activityNoList;
		return this;
	}

	public GetAutoScalingActivityLogListRequest addActivityNoListItem(String activityNoListItem) {
		if (this.activityNoList == null) {
			this.activityNoList = new ArrayList<String>();
		}
		this.activityNoList.add(activityNoListItem);
		return this;
	}

	 /**
	 * 액티비티번호리스트
	 * @return activityNoList
	**/
	public List<String> getActivityNoList() {
		return activityNoList;
	}

	public void setActivityNoList(List<String> activityNoList) {
		this.activityNoList = activityNoList;
	}

	public GetAutoScalingActivityLogListRequest pageNo(Integer pageNo) {
		this.pageNo = pageNo;
		return this;
	}

	 /**
	 * 페이지번호
	 * @return pageNo
	**/
	public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public GetAutoScalingActivityLogListRequest pageSize(Integer pageSize) {
		this.pageSize = pageSize;
		return this;
	}

	 /**
	 * 페이지사이즈
	 * @return pageSize
	**/
	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public GetAutoScalingActivityLogListRequest responseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
		return this;
	}

	 /**
	 * responseFormatType {json, xml}
	 * @return responseFormatType
	**/
	public String getResponseFormatType() {
		return responseFormatType;
	}

	public void setResponseFormatType(String responseFormatType) {
		this.responseFormatType = responseFormatType;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetAutoScalingActivityLogListRequest getAutoScalingActivityLogListRequest = (GetAutoScalingActivityLogListRequest) o;
		return Objects.equals(this.regionCode, getAutoScalingActivityLogListRequest.regionCode) &&
				Objects.equals(this.autoScalingGroupNo, getAutoScalingActivityLogListRequest.autoScalingGroupNo) &&
				Objects.equals(this.activityNoList, getAutoScalingActivityLogListRequest.activityNoList) &&
				Objects.equals(this.pageNo, getAutoScalingActivityLogListRequest.pageNo) &&
				Objects.equals(this.pageSize, getAutoScalingActivityLogListRequest.pageSize) &&
				Objects.equals(this.responseFormatType, getAutoScalingActivityLogListRequest.responseFormatType);
	}

	@Override
	public int hashCode() {
		return Objects.hash(regionCode, autoScalingGroupNo, activityNoList, pageNo, pageSize, responseFormatType);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetAutoScalingActivityLogListRequest {\n");
		
		sb.append("		regionCode: ").append(toIndentedString(regionCode)).append("\n");
		sb.append("		autoScalingGroupNo: ").append(toIndentedString(autoScalingGroupNo)).append("\n");
		sb.append("		activityNoList: ").append(toIndentedString(activityNoList)).append("\n");
		sb.append("		pageNo: ").append(toIndentedString(pageNo)).append("\n");
		sb.append("		pageSize: ").append(toIndentedString(pageSize)).append("\n");
		sb.append("		responseFormatType: ").append(toIndentedString(responseFormatType)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

