/*
 * vautoscaling
 * VPC Auto Scaling 관련 API<br/>https://ncloud.apigw.ntruss.com/vautoscaling/v2
 *
 * OpenAPI spec version: 2021-01-21T11:15:08Z
 *
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.vautoscaling.model;

import java.util.Objects;
import com.ncloud.vautoscaling.model.CommonCode;

/**
 * ScalingPolicy
 */
public class ScalingPolicy {
	private String autoScalingGroupNo = null;

	private String policyNo = null;

	private String policyName = null;

	private CommonCode adjustmentType = null;

	private Integer scalingAdjustment = null;

	private Integer minAdjustmentStep = null;

	private Integer coolDown = null;

	public ScalingPolicy autoScalingGroupNo(String autoScalingGroupNo) {
		this.autoScalingGroupNo = autoScalingGroupNo;
		return this;
	}

	 /**
	 * 오토스케일링그룹번호
	 * @return autoScalingGroupNo
	**/
	public String getAutoScalingGroupNo() {
		return autoScalingGroupNo;
	}

	public void setAutoScalingGroupNo(String autoScalingGroupNo) {
		this.autoScalingGroupNo = autoScalingGroupNo;
	}

	public ScalingPolicy policyNo(String policyNo) {
		this.policyNo = policyNo;
		return this;
	}

	 /**
	 * 정책번호
	 * @return policyNo
	**/
	public String getPolicyNo() {
		return policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public ScalingPolicy policyName(String policyName) {
		this.policyName = policyName;
		return this;
	}

	 /**
	 * 정책이름
	 * @return policyName
	**/
	public String getPolicyName() {
		return policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	public ScalingPolicy adjustmentType(CommonCode adjustmentType) {
		this.adjustmentType = adjustmentType;
		return this;
	}

	 /**
	 * 조정유형
	 * @return adjustmentType
	**/
	public CommonCode getAdjustmentType() {
		return adjustmentType;
	}

	public void setAdjustmentType(CommonCode adjustmentType) {
		this.adjustmentType = adjustmentType;
	}

	public ScalingPolicy scalingAdjustment(Integer scalingAdjustment) {
		this.scalingAdjustment = scalingAdjustment;
		return this;
	}

	 /**
	 * 조정값
	 * @return scalingAdjustment
	**/
	public Integer getScalingAdjustment() {
		return scalingAdjustment;
	}

	public void setScalingAdjustment(Integer scalingAdjustment) {
		this.scalingAdjustment = scalingAdjustment;
	}

	public ScalingPolicy minAdjustmentStep(Integer minAdjustmentStep) {
		this.minAdjustmentStep = minAdjustmentStep;
		return this;
	}

	 /**
	 * 최소조정폭
	 * @return minAdjustmentStep
	**/
	public Integer getMinAdjustmentStep() {
		return minAdjustmentStep;
	}

	public void setMinAdjustmentStep(Integer minAdjustmentStep) {
		this.minAdjustmentStep = minAdjustmentStep;
	}

	public ScalingPolicy coolDown(Integer coolDown) {
		this.coolDown = coolDown;
		return this;
	}

	 /**
	 * 쿨다운
	 * @return coolDown
	**/
	public Integer getCoolDown() {
		return coolDown;
	}

	public void setCoolDown(Integer coolDown) {
		this.coolDown = coolDown;
	}


	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ScalingPolicy scalingPolicy = (ScalingPolicy) o;
		return Objects.equals(this.autoScalingGroupNo, scalingPolicy.autoScalingGroupNo) &&
				Objects.equals(this.policyNo, scalingPolicy.policyNo) &&
				Objects.equals(this.policyName, scalingPolicy.policyName) &&
				Objects.equals(this.adjustmentType, scalingPolicy.adjustmentType) &&
				Objects.equals(this.scalingAdjustment, scalingPolicy.scalingAdjustment) &&
				Objects.equals(this.minAdjustmentStep, scalingPolicy.minAdjustmentStep) &&
				Objects.equals(this.coolDown, scalingPolicy.coolDown);
	}

	@Override
	public int hashCode() {
		return Objects.hash(autoScalingGroupNo, policyNo, policyName, adjustmentType, scalingAdjustment, minAdjustmentStep, coolDown);
	}


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ScalingPolicy {\n");
		
		sb.append("		autoScalingGroupNo: ").append(toIndentedString(autoScalingGroupNo)).append("\n");
		sb.append("		policyNo: ").append(toIndentedString(policyNo)).append("\n");
		sb.append("		policyName: ").append(toIndentedString(policyName)).append("\n");
		sb.append("		adjustmentType: ").append(toIndentedString(adjustmentType)).append("\n");
		sb.append("		scalingAdjustment: ").append(toIndentedString(scalingAdjustment)).append("\n");
		sb.append("		minAdjustmentStep: ").append(toIndentedString(minAdjustmentStep)).append("\n");
		sb.append("		coolDown: ").append(toIndentedString(coolDown)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n		");
	}

}

